api = "0.8"

[buildpack]
  description = "A buildpack for installing the Go modules using dep"
  homepage = "https://github.com/paketo-buildpacks/dep-ensure"
  id = "paketo-buildpacks/dep-ensure"
  name = "Paketo Dep Ensure Buildpack"
  keywords = ["go", "dep", "ensure"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/dep-ensure/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"
