api = "0.4"

[buildpack]
  id = "paketo-buildpacks/dep-ensure"
  name = "Paketo Dep Ensure Buildpack"
  homepage = "https://github.com/paketo-buildpacks/dep-ensure"

[metadata]
  include-files = [ "bin/build", "bin/detect", "bin/run", "buildpack.toml" ]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
